url: https://toastmaster-qhd.github.io
baseurl: ''

# Site settings
title: Toastmaster
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.'

# Team names, titles and social links
people:
  - name: Peter Wang
    pic: 1
    position: COO and Maintainer Of This Site
    social:
      - title: twitter
        url: https://twitter.com/happypeter1983

  - name: Ben
    pic: 2
    position: President
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #
  - name: Ping
    pic: 3
    position: CFO
    social:
      - title: wechat
        url: #
  - name: Tricia
    pic: 4
    position: Secretary
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #
  - name: Catherine
    pic: 5
    position: Hostess
    social:
      - title: wechat
        url: https://toastmaster-qhd.github.io/img/team/catherine.jpg
  - name: Yolanda
    pic: 6
    position: Hostess
    social:
      - title: wechat
        url: https://toastmaster-qhd.github.io/img/team/yolanda.jpg
  - name: Lily
    pic: 7
    position: General Evaluator
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #

  - name: XinZe Shi
    pic: 8
    position: VP
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #
  - name: Candy
    pic: 9
    position: Active Contributor
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/toastmaster-qhd

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
